### ISSUE TITLE
Programmatically adding image

### ISSUE THREAD

**Issue by yoshu** [evgenyneu/ios-imagescroll#2]
Hello, it works great for image loaded via Storyboard, but it would be more useful loading image programmatically. How do we do that? There seems to be a problem with scaling the image on load. It opens in full size. In a scenario:
- (void) viewDidLoad {
  [self loadImage];
  }
- (void) loadImage {
  //open or download image 
  //...
  [self setImage:image];
  }
- (void) setImage:(UIImage *)image {
  self.imageView.image = image; 
  [self initZoom]; // doesn't scale image down when first loaded
  }

Tried some imageView size settings, like setting self.imageView.frame to image size before adding Image, but didn't succeed in loading the image scaled down to fit the screen.

Bonus question - image smaller than screen get scaled up, how to display them centered and without zoom?

**Comment by evgenyneu** [comment]
Hi, thanks for the feedback. Updated the code, now it sets image programmatically as you wanted. The trick was to increase content hugging priority for image view.

As for the small image - it probably should work now too. If not - try playing with 'hugging' and 'compression resistance' values.

There is another issue that becomes noticeable with small images. Sometimes on zooming it displays image off-center. Issue looks random. Big images also have the issue, though it is less noticeable.

**Comment by yoshu** [comment]
Thanks for fast reply! I didn't think of content hugging. In the end I've just used [self.imageView sizeToFit]; right after self.imageView.image = [UIImage...], but I will try to use your solution instead, as it might help with small images.

I'm temporarily correcting the centering with:

```
- (void) scrollViewDidZoom:(UIScrollView *)scrollView {
    [self centeredFrameForScrollView];
}
- (void) centeredFrameForScrollView {
    CGSize boundsSize = self.scrollView.bounds.size;
    CGRect frameToCenter = self.imageView.frame;
    // center horizontally
    if (frameToCenter.size.width < boundsSize.width) {
        frameToCenter.origin.x = (boundsSize.width - frameToCenter.size.width) / 2;
    }
    else {
        frameToCenter.origin.x = 0;
    }
    // center vertically
    if (frameToCenter.size.height < boundsSize.height) {
        frameToCenter.origin.y = (boundsSize.height - frameToCenter.size.height) / 2;
    }
    else {
        frameToCenter.origin.y = 0;
    }
    self.imageView.frame = frameToCenter;
}
```

But it's an ugly fix as you can often see the image moving slightly to fix the position after it ends zooming. Not really sure how to keep the imageView in the center of screen, while zooming. Currently, the image is "jumping" in all directions while zooming in or out.

**Comment by evgenyneu** [comment]
You are welcome. This "jumping" issue was very annoying indeed. So I decided to change the approach. It now updates the `constant` values for the constraints on zooming.

Also, added a button to switch between small and large images, to make testing easier.

I hope that helps. Please let me know if you notice any other issues.

**Comment by yoshu** [comment]
The zooming is, indeed, more smooth now, which also makes the position correction less noticeable. 
Great, helpful project, thanks for these updates.
