### ISSUE TITLE
Smaller images

### ISSUE THREAD

**Issue by cojoj** [evgenyneu/ios-imagescroll#5]
I must admit that you've done a grat job with this project!

Anyway, I have some concerns... 

Firstly when you zoom in a little bit a small picture it seems like it is put in a bigger container view so you can drag it and put it elsewhere - strange that **it is not blocking scrolling until the image is bigger than scroll view**. Any solution for that?

Secondly, is it possible to zoom in smaller images to fit to the screen size (`scrollView`)? I know the may get blurry etc. but keeping them small in the center is odd for me.

I would appreciate any help cause I'm stuck and I have nowhere to go without this! :grinning:

**Comment by cojoj** [comment]
After some observation... This only happens under **iOS 8**. When I run this on iOX 7.X device everything works like it should!

**Comment by evgenyneu** [comment]
Thanks @cojoj!
