### ISSUE TITLE
Image view centered with extra padding 

### ISSUE THREAD

**Issue by hggz** [evgenyneu/ios-imagescroll#8]
Hey,

I really appreciate all the work you've done on this library to help illustrate this concept that's beenn causing me grief. Hopefully you can help me out with this.

I implemented this approach however my ui image view is centered with more padding on the leading and trailing sides. The width and height should be 320 however it's constrained to 250. The mask of the image should be aspect fit however instead of clipping to the sides of the view like your example, it keeps getting that extra padding. Any advice you can provide would be greatly appreciated!

**Comment by evgenyneu** [comment]
Hi @hgonzalez94, thanks. Nothing rings a bell so far. Is the original image width smaller than 320 pixels? It would help if you could isolate your problem in a separate app. There are so many things that can affect the result, it is really hard to say without isolating it.

**Comment by hggz** [comment]
Yes. This photo is 460 x 460 px. It's getting shrunk to these proportions 
![screen shot 2015-02-14 at 10 18 08 pm](https://cloud.githubusercontent.com/assets/6015420/6202383/2162d5ce-b49c-11e4-8679-262997c7bb46.png)

**Comment by evgenyneu** [comment]
Is your phone screen 2x (iPhone 4/5) or 3x (iPhone 6 Plus)?

**Comment by hggz** [comment]
2x. Specifically an iPhone 5

**Comment by evgenyneu** [comment]
Ah, maybe your image needs to be at least 640px (2 x 320px) wide to fill full screen width on iPhone5.

**Comment by hggz** [comment]
Yeah, I was beginning to definitely think it was the size of the image. Do you have any idea how to alter the constraints to compensate for this? I was able to have a similar implementation done programmatically but I've really been struggling trying to get a pure auto layout approach working. I feel this is the closest solution I've been able to find online.

**Comment by evgenyneu** [comment]
If the image is smaller than screen it is not zoomed in currently to avoid blurriness.
I removed this check in `stretch_smaller_image` branch. Also, the max zoom on the scroll view was `3`, I increased it. 

Diff: https://github.com/evgenyneu/ios-imagescroll/commit/061af08f6a417aca55c85919e0feac5a7075fa5a

**Comment by hggz** [comment]
Hmm, I played around with the initial zoom values actually and I still didn't achieve the desired results. This technique works very well with large images however for smaller ones its having some trouble. I think I may have to go with the programmatic approach.

**Comment by evgenyneu** [comment]
If you isolate this screen of your app into a github repo I will have a
look.

**Comment by hggz** [comment]
I'll do that, thanks!

**Comment by hggz** [comment]
Hey evgen, just a heads up. I made a blank project with the same configuration as the area of my app that I'm trying to test, and your method appears to work even on the iphone 5 and with a photo of the same dimensions. I'm going to take a closer look at my project before I do anything else.

**Comment by evgenyneu** [comment]
Looks like this one is resolved. Feel free to open it if it's not. Thanks.
